stages:
  - build
  - deploy

build-dev:
  stage: build
  only:
    - dev
  image: docker:18.09.7-dind
  services:
    - name: docker:18.09.7-dind

  before_script:
  - docker logout $CI_REGISTRY_URL
  - mkdir ~/.docker && touch ~/.docker/config.json && cp $DOCKER_AUTH_CONFIG ~/.docker/config.json
  - docker login $CI_REGISTRY_URL
  script:
#    - mv $DEV_ENV .env
#    - cat .env
    - docker build --tag $CI_REGISTRY_URL/$DEV_REGISTRY_NAME:$CI_COMMIT_SHA --tag $CI_REGISTRY_URL/$DEV_REGISTRY_NAME:latest -f compose/production/django/Dockerfile .

    - docker push $CI_REGISTRY_URL/$DEV_REGISTRY_NAME:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_URL/$DEV_REGISTRY_NAME:latest


deploy-dev:
  image: alpine
  stage: deploy

  script:
    - chmod og= $DEV_ID_RSA
    - apk update && apk add openssh-client

    - ssh -i $DEV_ID_RSA -o StrictHostKeyChecking=no $DEV_SERVER_USER@$DEV_SERVER_IP "cd /opt/omnichat && docker compose pull && docker compose --rm django python manage.py migrate && docker compose up -d"
  only:
    - dev