CORECHAT_TO_CHAT_SERVICE = "CoreChat.To.ChatService"            # CORECHAT OF OMNICHAT SERVICE -> WEBSOCKET OMNICHAT
CORECHAT_TO_WEBHOOK_FACEBOOK = "CoreChat.To.Webhook.FaceBook"   # CORECHAT OF OMNICHAT SERVICE -> WS FACEBOOK
CORECHAT_TO_WEBHOOK_LIVECHAT = "CoreChat.To.Webhook.LiveChat"   # CORECHAT OF OMNICHAT SERVICE -> WS LIVECHAT ANONYMOUS
CORECHAT_TO_WEBHOOK_ZALO = "CoreChat.To.Webhook.Zalo"   # CORECHAT OF OMNICHAT SERVICE -> WS ZALO

CHAT_SERVICE_TO_CORECHAT_SUBSCRIBE = "ChatService.To.CoreChat.*"            # OMNICHAT SERVICE -> CORECHAT
CHAT_SERVICE_TO_CORECHAT_PUBLISH = "ChatService.To.CoreChat"            # OMNICHAT SERVICE -> CORECHAT

WEBHOOK_TO_CORECHAT_MESSAGE = "Webhook.To.CoreChat.Message"     # SERVICE WEBHOOK -> CORECHAT

WEBHOOK_TO_CORECHAT_MESSAGE_OLD = "omniChat.message.receive.*"     # SERVICE WEBHOOK -> CORECHAT OLD
