CORECHAT_TO_CHAT_SERVICE = "CoreChat.To.ChatService"            # CORECHAT OF OMNICHAT SERVICE -> WEBSOCKET OMNICHAT

CORECHAT_TO_WEBSOCKET_FACEBOOK = "CoreChat.To.ChatWs.FaceBook"   # CORECHAT OF OMNICHAT SERVICE -> WS FACEBOOK
CORECHAT_TO_WEBSOCKET_LIVECHAT = "CoreChat.To.ChatWs.LiveChat"   # CORECHAT OF OMNICHAT SERVICE -> WS LIVECHAT
CORECHAT_TO_WEBSOCKET_ZALO = "CoreChat.To.ChatWs.Zalo"   # CORECHAT OF OMNICHAT SERVICE -> WS ZALO

CORECHAT_TO_WEBHOOK_LIVECHAT = "CoreChat.To.Webhook.LiveChat"   # CORECHAT OF OMNICHAT SERVICE -> WEBHOOK LIVECHAT ANONYMOUS

CHAT_SERVICE_TO_CORECHAT_SUBSCRIBE = "ChatService.To.CoreChat.*"            # OMNICHAT SERVICE -> CORECHAT
CHAT_SERVICE_TO_CORECHAT_PUBLISH = "ChatService.To.CoreChat"            # OMNICHAT SERVICE -> CORECHAT

WEBHOOK_TO_CORECHAT_MESSAGE = "Webhook.To.CoreChat.Message.*"     # SERVICE WEBHOOK -> CORECHAT

WEBHOOK_TO_CORECHAT_MESSAGE_OLD = "omniChat.message.receive.*"     # SERVICE WEBHOOK -> CORECHAT OLD

REMINDER_CHAT_SERVICE_TO_WEBSOCKET = "reminder.ChatService.To.WebSocket." # REMINDER FOR ROOM
