# Generated by Django 3.2.14 on 2022-09-13 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('name_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('name_agent_active', models.BooleanField(default=True)),
                ('is_popup', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('icon', models.BooleanField(default=False)),
                ('size', models.JSONField(blank=True, null=True)),
                ('location', models.CharField(choices=[('top_right', 'Top Right'), ('top_left', 'Top Left'), ('bottom_right', 'Bottom Right'), ('bottom_left', 'Bottom Left')], default='top_right', max_length=20)),
                ('start_btn', models.CharField(blank=True, max_length=255, null=True)),
                ('is_introduce_message', models.BooleanField(default=False)),
                ('introduce_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_start_message', models.BooleanField(default=False)),
                ('start_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_offline_message', models.BooleanField(default=False)),
                ('offline_message', models.CharField(blank=True, max_length=255, null=True)),
                ('is_registerinfor', models.BooleanField(default=False)),
                ('script', models.CharField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LiveChatRegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.JSONField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('live_chat_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_id', to='live_chat.livechat')),
            ],
        ),
    ]
