# Generated by Django 3.2.14 on 2022-09-13 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0003_userapp'),
        ('live_chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiveChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_live_chat_room', to='app_connect.room')),
            ],
        ),
    ]
