# Generated by Django 3.2.14 on 2022-09-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0003_livechat_icon_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livechat',
            name='icon_context',
        ),
        migrations.AddField(
            model_name='livechat',
            name='icon_content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
