# Generated by Django 3.2.14 on 2022-09-20 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0004_auto_20220919_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechat',
            name='is_show_avatar',
            field=models.BooleanField(default=False),
        ),
    ]
