# Generated by Django 3.2.14 on 2022-09-26 08:26

from django.db import migrations, models
import sop_chat_service.live_chat.utils


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0005_livechat_is_show_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='', validators=[sop_chat_service.live_chat.utils.file_size]),
        ),
    ]
