# Generated by Django 3.2.14 on 2022-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_chat', '0007_livechat_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechat',
            name='introduce_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='livechat',
            name='offline_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='livechat',
            name='start_message',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
