# Generated by Django 3.2.14 on 2022-09-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0003_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=30),
        ),
    ]
