# Generated by Django 3.2.14 on 2022-09-20 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0007_attachment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='refresh_token_page',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fanpage',
            name='last_subscribe',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
