# Generated by Django 3.2.14 on 2022-09-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0009_fanpage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpage',
            name='access_token_page',
            field=models.CharField(blank=True, max_length=12288, null=True),
        ),
        migrations.AlterField(
            model_name='fanpage',
            name='refresh_token_page',
            field=models.CharField(blank=True, max_length=12288, null=True),
        ),
    ]
