# Generated by Django 3.2.14 on 2022-09-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0010_auto_20220925_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
