# Generated by Django 3.2.14 on 2022-09-26 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0011_message_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('all', 'All'), ('processing', 'Processing'), ('completed', 'Completed'), ('expired', 'Expired')], default='processing', max_length=30),
        ),
    ]
