# Generated by Django 3.2.14 on 2022-09-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0012_alter_room_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('livechat', 'Live Chat')], default='facebook', max_length=30),
        ),
    ]
