# Generated by Django 3.2.14 on 2022-10-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0013_fanpage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='fanpage_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
