# Generated by Django 3.2.14 on 2022-10-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0014_fanpage_fanpage_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('zalo', 'Zalo'), ('livechat', 'Live Chat')], default='facebook', max_length=30),
        ),
    ]
