# Generated by Django 3.2.14 on 2022-10-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0015_alter_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fanpage',
            name='last_subscribe',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
