# Generated by Django 3.2.14 on 2022-10-14 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0016_alter_fanpage_last_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('value', models.CharField(blank=True, max_length=500, null=True)),
                ('mid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_message_id', to='app_connect.message')),
            ],
        ),
    ]
