# Generated by Django 3.2.14 on 2022-10-28 03:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0017_servicesurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='fanpage',
            name='group_user',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='fanpage',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fanpage',
            name='setting_chat',
            field=models.CharField(default='only_me', max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='admin_room_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='block_admin',
            field=models.BooleanField(null=True),
        ),
    ]
