# Generated by Django 3.2.14 on 2022-11-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0018_auto_20221028_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesurvey',
            name='value',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
