# Generated by Django 3.2.14 on 2022-11-07 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0020_logmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='color',
            new_name='label_id',
        ),
        migrations.RemoveField(
            model_name='label',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='label',
            name='name',
        ),
    ]
