# Generated by Django 3.2.14 on 2022-11-09 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_connect', '0021_auto_20221107_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='room_id',
        ),
        migrations.AddField(
            model_name='reminder',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='AssignReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=30, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('time_reminder', models.IntegerField(blank=True, null=True)),
                ('repeat_time', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reminder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assign_reminder', to='app_connect.reminder')),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_reminder', to='app_connect.room')),
            ],
        ),
    ]
